n = str(input('Digite seu nome completo: ')).strip()
ma = n.upper()
mi = n.lower()
r = n.split()
w = ''.join(r)
y = len(w)
z = len(r[0])
print('Analisando seu nome...')
print('Seu nome todo em maiúsculo: {}'.format(ma))
print('Seu nome todo em minúsculo: {}'.format(mi))
print('Seu primeiro nome é {} e ele possui {} letras'.format(r[0], z))
print('O seu nome possui ao todo {} letras'.format(y))
